### ISSUE TITLE
Issues using it with postgres on ubuntu

### ISSUE THREAD

**Issue by Six-wars** [caioariede/django-location-field#105]
I setup the django app following the steps, I also use postgres but when I try to makemigrations and migrate I get this error

```
(decomagna) sam@sam-Lenovo-G51-35:~/code/DECOMAGNA/decomagna$ python3 manage.py migrate
/home/sam/.local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Operations to perform:
  Apply all migrations: admin, auth, common, contenttypes, inventory, pages, sessions
Running migrations:
  Applying inventory.0008_previousjob_location...Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sam/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/sam/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sam/.local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sam/.local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/sam/.local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/sam/.local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/home/sam/.local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/sam/.local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/sam/.local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/sam/.local/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/sam/.local/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 84, in database_forwards
    field,
  File "/home/sam/.local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 421, in add_field
    definition, params = self.column_sql(model, field, include_default=True)
  File "/home/sam/.local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 157, in column_sql
    db_params = field.db_parameters(connection=self.connection)
  File "/home/sam/.local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 697, in db_parameters
    type_string = self.db_type(connection)
  File "/home/sam/.local/lib/python3.6/site-packages/django/contrib/gis/db/models/fields.py", line 105, in db_type
    return connection.ops.geo_db_type(self)
AttributeError: 'DatabaseOperations' object has no attribute 'geo_db_type'
```

This is what I have in the models file

```
from django.contrib.gis.geos import Point
from location_field.models.spatial import LocationField

class PreviousJob(models.Model):
    ...
    location = LocationField(based_fields=['city'], zoom=7, default=Point(1.0, 1.0))
    ...
```

**Comment by caioariede** [comment]
I think you're not using a spatial database (PostGIS in this case):

https://docs.djangoproject.com/en/2.1/ref/contrib/gis/tutorial/#configure-settings-py

If you're using Postgres but not PostGIS, you should be using `PlainLocationField`
